In [1]:

import numpy as np

d = 64                           # dimension
nb = 100000                      # database size
nq = 10000                       # nb of queries
np.random.seed(1234)             # make reproducible
xb = np.random.random((nb, d)).astype('float32')
xb[:, 0] += np.arange(nb) / 1000.
xq = np.random.random((nq, d)).astype('float32')
xq[:, 0] += np.arange(nq) / 1000.

import faiss

nlist = 100
k = 4
quantizer = faiss.IndexFlatL2(d)  # the other index
index = faiss.IndexIVFFlat(quantizer, d, nlist, faiss.METRIC_L2)
# here we specify METRIC_L2, by default it performs inner-product search

assert not index.is_trained
index.train(xb)
assert index.is_trained

index.add(xb)                  # add may be a bit slower as well
D, I = index.search(xq, k)     # actual search
print(I[-5:])                  # neighbors of the 5 last queries
index.nprobe = 10              # default nprobe is 1, try a few more
D, I = index.search(xq, k)
print(I[-5:])                  # neighbors of the 5 last queries

[[ 9900  9309  9810 10048]
 [11055 10895 10812 11321]
 [11353 10164  9787 10719]
 [10571 10664 10632 10203]
 [ 9628  9554  9582 10304]]
[[ 9900 10500  9309  9831]
 [11055 10895 10812 11321]
 [11353 11103 10164  9787]
 [10571 10664 10632  9638]
 [ 9628  9554 10036  9582]]


In [2]:

from langchain_community.chat_models import ChatOpenAI
from langchain_community.embeddings import OpenAIEmbeddings
from langchain_community.vectorstores import FAISS

import datasets
from envs.babilong.babilong_utils import TaskDataset

sample_size = 16000
top_k = 5


# openai.api_key = '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'
openai_key = "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"
OPENAI_API_KEY = "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"
# os.environ["OPENAI_API_KEY"] = os.getenv("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")

model = ChatOpenAI(
    openai_api_key=openai_key,
    #model='gpt-3.5-turbo',
    model='gpt-4-1106-preview'
)


embed_model = OpenAIEmbeddings(openai_api_key=openai_key,
                               model="text-embedding-ada-002")

/home/griver/anaconda3/envs/rmt/lib/python3.9/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
/home/griver/anaconda3/envs/rmt/lib/python3.9/site-packages/langchain_core/_api/deprecation.py:117: LangChainDeprecationWarning: The class `langchain_community.chat_models.openai.ChatOpenAI` was deprecated in langchain-community 0.0.10 and will be removed in 0.2.0. An updated version of the class exists in the langchain-openai package and should be used instead. To use it run `pip install -U langchain-openai` and import as `from langchain_openai import ChatOpenAI`.
  warn_deprecated(
/home/griver/anaconda3/envs/rmt/lib/python3.9/site-packages/langchain_core/_api/deprecation.py:117: LangChainDeprecationWarning: The class `langchain_community.embeddings.openai.OpenAIEmbeddings` was deprecated in langchain-community 0.0.9 and wi

In [3]:
ds = datasets.load_from_disk('../data/pg19-test-with-sentences')

In [5]:
noise_sentences = ds['sentences'][0][:100]

In [20]:
#embeddings = embed_model.embed_documents(noise_sentences)
noise_embeds = embeddings

In [21]:
text_embedding_pairs = zip(noise_sentences, noise_embeds)
faiss = FAISS.from_embeddings(text_embedding_pairs, embed_model)

In [22]:
sum(len(s) for s in noise_sentences)

13826

In [24]:
test_path = "../data/tasks_1-20_v1-2/en-10k/qa1_single-supporting-fact_test.txt"
task_dataset_test = TaskDataset(test_path)

In [28]:
facts = task_dataset_test[0]['facts']
facts_embeds = embed_model.embed_documents(facts)

In [30]:
len(facts_embeds), len(facts)

(2, 2)

In [32]:
faiss.add_embeddings(zip(facts, facts_embeds))

['2edfd847-11e4-45a7-b9ac-8e00a3325577',
 '2a9042ee-b8dd-46d5-af31-8ee7261dbfd4']

In [40]:
top_k = 3
retriever = faiss.as_retriever(search_kwargs={"k": top_k})

In [41]:

retrieved_relevant_docs = retriever.get_relevant_documents(task_dataset_test[0]['question'])
print('retrieved_relevant_docs', retrieved_relevant_docs)

retrieved_relevant_docs [Document(page_content='John travelled to the hallway.'), Document(page_content='Paul.'), Document(page_content='Mr.')]


In [44]:
print(facts)

['John travelled to the hallway.' 'Mary journeyed to the bathroom.']


In [4]:
from transformers import AutoTokenizer
tokenizer = AutoTokenizer.from_pretrained('gpt2')

In [40]:
book_start = 80
book_end = 100
total_length = 0
total_sent = 0
for i, book in enumerate(ds['sentences'][book_start:book_end]):
    total_sent += len(book)
    book_len = sum( [len(tokenizer.encode(s)) for s in book] )
    total_length += book_len
    print(f"book #{i+1}, book_len: {book_len}, total_len: {total_length}, num sentences: {total_sent}")
    

book #1, book_len: 354411, total_len: 354411, num sentences: 10883
book #2, book_len: 30861, total_len: 385272, num sentences: 11900
book #3, book_len: 139781, total_len: 525053, num sentences: 16733
book #4, book_len: 61206, total_len: 586259, num sentences: 20385
book #5, book_len: 27412, total_len: 613671, num sentences: 20876
book #6, book_len: 42221, total_len: 655892, num sentences: 25284
book #7, book_len: 55956, total_len: 711848, num sentences: 27297
book #8, book_len: 37267, total_len: 749115, num sentences: 27879
book #9, book_len: 63626, total_len: 812741, num sentences: 30139
book #10, book_len: 119851, total_len: 932592, num sentences: 38300
book #11, book_len: 210467, total_len: 1143059, num sentences: 46612
book #12, book_len: 264784, total_len: 1407843, num sentences: 53396
book #13, book_len: 222864, total_len: 1630707, num sentences: 62103
book #14, book_len: 254483, total_len: 1885190, num sentences: 69861
book #15, book_len: 39367, total_len: 1924557, num sentences

In [35]:
import itertools
print(len(ds['sentences']))
sentences = list(itertools.chain.from_iterable(ds['sentences'][book_start:book_end]))

100


In [36]:
len(sentences)

85308

In [37]:
sent_embeds = embed_model.embed_documents(sentences)

In [38]:
data = dict(sentences=sentences, embeddings=sent_embeds)

In [41]:
len(data['embeddings'])

85308

In [42]:
import torch as th
th.save(data, "../data/pg19_eval_sentences_5.pkl")

In [43]:
!ls ../data/

pg19_eval_sentences_1.pkl  pg19-test-with-sentences
pg19_eval_sentences_2.pkl  pg19-test-with-sentences.tar
pg19_eval_sentences_3.pkl  tasks_1-20_v1-2
pg19_eval_sentences_4.pkl  tasks_1-20_v1-2.zip
pg19_eval_sentences_5.pkl


huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)


In [59]:
del a